### ISSUE TITLE
Get the syntax working within Neovim

### ISSUE THREAD

**Issue by HALL9kv0** [tsoj/tree-sitter-cpp2#1]
First of all, thank you for your contribution to the cpp2 project! 
I'm somewhat of a new neovim user, and I was trying to add the syntax into my nvim configuration. 
Is there any chance you could share how to get it working within nvim? I am only familiar with the [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter
) (:TSInstall) way of installing them. Perhaps they can add it to their list!

Thanks again!

**Comment by tsoj** [comment]
I am not familiar with Neovim unfortunately, but if I understood correctly, @zaucy managed to make it work. You might need to adjust the [highlight names](https://tree-sitter.github.io/tree-sitter/syntax-highlighting#theme) in [queries/highlights.scm](https://github.com/tsoj/tree-sitter-cpp2/blob/main/queries/highlights.scm), because currently they are set to be used with Zed, and I think `@emphasis` and `@emphasis.strong` aren't defaults in nvim.

**Comment by zaucy** [comment]
> you might need to adjust the [highlight names](https://tree-sitter.github.io/tree-sitter/syntax-highlighting#theme) in [queries/highlights.scm](https://github.com/tsoj/tree-sitter-cpp2/blob/main/queries/highlights.scm)

yep, exactly. I did some random adjustments in my queries to make it look okay-ish. Nothing perfect as I only spent a little bit of time on it. If you have `Telescope` installed you can see the various highlights you have access to in your neovim environment `:Telescope highlights`.

To setup a parser that's not a default with nvim-treesitter add it like so:

```lua
local parsers = require("nvim-treesitter.parsers").get_parser_configs()
parsers.cpp2 = {
	install_info = {
		url = "https://github.com/tsoj/tree-sitter-cpp2.git",
		files = { "src/parser.c", "src/scanner.c" },
		branch = "main",
		generate_requires_npm = false,
		requires_generate_from_grammar = false,
	},
}

require("nvim-treesitter.configs").setup({
	auto_install = false,
	highlight = {
		enable = true,
	},
})
```

after that you can do `:TSInstall cpp2`

see `:help nvim-treesitter-modules` for the configs setup
you can also look at my setup if you'd like some reference https://github.com/zaucy/init/blob/main/nvim-config-minimal/lua/plugins/treesitter.lua (my poorly made highlights are also in there :P)

**Comment by HALL9kv0** [comment]
Thank you very much both! That was very very helpful!!!
